@switch($section)
    @case('addpost')
        @include('template/addpost')
        @break
    @case('addpostTransfers')
        @include('template/addpostTransfers')
        @break
    @case('listpost')
        @include('template/listpost')
        @break
    @case('listpostTransfers')
        @include('template/listpostTransfers')
        @break
    @case('seepost')
        @include('template/seepost')
        @break
    @case('seepostTransfers')
        @include('template/seepostTransfers')
        @break
    @case('admin')
        @include('template/admin')
        @break
    @case('listusers')
        @include('template/listusers')
        @break
    @case('addusers')
        @include('template/addusers')
        @break
    @case('seeusers')
        @include('template/seeusers')
        @break
    @default
        
@endswitch